version: 0.0
os: linux
files:
 - source: /
   destination: /opt/invasion-bot
hooks:
  BeforeInstall:
    - location: scripts/cleanup_directory
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/set_permissions_and_install_deps
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_bot
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_bot
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_bot_running
      timeout: 300
      runas: root