version: 0.0
os: linux
files:
 - source: /
   destination: /opt/invasion-bot
hooks:
  BeforeInstall:
    - location: scripts/stop_bot
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/set_permissions
      timeout: 300
      runas: root
    - location: scripts/install_app_dependencies
      timeout: 300
      runas: bot-user
  ApplicationStart:
    - location: scripts/start_bot
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_bot
      timeout: 300
      runas: root