#!/bin/bash
sudo cp /opt/.invasion_bot_secrets /opt/invasion-bot/.env.secret
sudo chown -R bot-user:bot-user /opt/invasion-bot
sudo chmod +x /opt/invasion-bot/discord_bot.py
cd /opt/invasion-bot
sudo -H -u bot-user bash -c 'python3 -m pip install -r requirements.txt'